wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
batch-of-patches-size:
  desc: null
  value: 2
dataset-name:
  desc: null
  value: hecktor-crS_rs113
learning-rate:
  desc: null
  value: 0.0003
num-epochs:
  desc: null
  value: 16
patch-size:
  desc: null
  value:
  - 128
  - 128
  - 32
start-epoch:
  desc: null
  value: 1
train-subset-name:
  desc: null
  value: crossval-CHUM-training
val-subset-name:
  desc: null
  value: crossval-CHUM-validation
