wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
dataset:
  desc: null
  value: hecktor_train_crS_rs113
patch_size:
  desc: null
  value:
  - 128
  - 128
  - 32
