
# Hardware
hardware-config:
  device: cuda  # Default device
  enable-distributed: True


# Training config
training-config:
  train-subset-name: crossval-CHGJ-training
  loss-name: wce+dice
  num-epochs: 30
  learning-rate: 0.0001
  use-lr-scheduler: True
  enable-checkpointing: True
  checkpoint-step: 5
  checkpoint-root-dir: ./model_checkpoints
  continue-from-checkpoint: False
  load-checkpoint-filename: None 


# Validation config
validation-config:
  val-subset-name: crossval-CHGJ-validation


# WandB logging config
logging-config:
  run-name: default-run
  enable-wandb: True
  wandb-entity: cnmy-ro
  wandb-project: hn-gtv-segmentation
  