
# Key-word arguments for the Trainer class
trainer-kwargs:

  # Hardware config dict
  hardware_config:
    device: cuda  # Default device
    enable-distributed: True


  # Training config dict
  training_config:
    train-subset-name: crossval-CHUM-training
    loss-name: wce+dice
    num-epochs: 120
    learning-rate: 0.0002
    use-lr-scheduler: True
    enable-checkpointing: True
    checkpoint-step: 5
    checkpoint-root-dir: ./model_checkpoints
    continue-from-checkpoint: false
    load-checkpoint-filename: None


  # Validation config dict
  validation_config:
    val-subset-name: crossval-CHUM-validation


  # WandB logging config dict
  logging_config:
    run-name: default-run
    enable-wandb: True
    wandb-entity: cnmy-ro
    wandb-project: hn-gtv-segmentation
    