
# Hardware
hardware-config:
  device: cuda  # Default device
  enable-distributed: False


# Training config
training-config:
  train-subset-name: crossval-CHUM-training
  loss-name: wce+dice
  num-epochs: 21
  learning-rate: 0.0003
  use-lr-scheduler: False
  enable-checkpointing: True
  checkpoint-step: 3
  checkpoint-root-dir: ./model_checkpoints
  continue-from-checkpoint: False
  load-checkpoint-filename: None


# Validation config
validation-config:
  val-subset-name: crossval-CHUM-validation


# WandB logging config
logging-config:
  run-name: default-run
  enable-wandb: True
  wandb-entity: cnmy-ro
  wandb-project: hn-gtv-segmentation
  