wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
batch_of_patches_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0003
patch_size:
  desc: null
  value:
  - 128
  - 128
  - 32
